services:
  - type: web
    name: ai-maintenance-tracker
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: postgresql+psycopg2://REPLACE_WITH_INTERNAL_URL
      - key: TZ
        value: Asia/Riyadh
